## CountVectorizer

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
corpus = "Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured, object-oriented and functional programming."


In [5]:
lst=[]
for k in corpus.split('.'):
    lst.append(k)

lst

['Python is a high-level, general-purpose programming language',
 ' Its design philosophy emphasizes code readability with the use of significant indentation',
 ' Python is dynamically typed and garbage-collected',
 ' It supports multiple programming paradigms, including structured, object-oriented and functional programming',
 '']

In [14]:
lst = [k for k in lst if k]
lst

['Python is a high-level, general-purpose programming language',
 ' Its design philosophy emphasizes code readability with the use of significant indentation',
 ' Python is dynamically typed and garbage-collected',
 ' It supports multiple programming paradigms, including structured, object-oriented and functional programming']

In [18]:
import pandas as pd
df = pd.DataFrame(lst,columns=['text'])
df['output']=[1,1,0,0]
display(df)

text  output
0  Python is a high-level, general-purpose progra...       1
1   Its design philosophy emphasizes code readabi...       1
2   Python is dynamically typed and garbage-colle...       0
3   It supports multiple programming paradigms, i...       0

In [19]:
BOW = CountVectorizer()
doc_matrix = BOW.fit_transform(df['text'])
doc_matrix

<4x34 sparse matrix of type '<class 'numpy.int64'>'
	with 38 stored elements in Compressed Sparse Row format>

In [20]:
BOW.vocabulary_

{'python': 25,
 'is': 12,
 'high': 9,
 'level': 16,
 'general': 8,
 'purpose': 24,
 'programming': 23,
 'language': 15,
 'its': 14,
 'design': 3,
 'philosophy': 22,
 'emphasizes': 5,
 'code': 1,
 'readability': 26,
 'with': 33,
 'the': 30,
 'use': 32,
 'of': 19,
 'significant': 27,
 'indentation': 11,
 'dynamically': 4,
 'typed': 31,
 'and': 0,
 'garbage': 7,
 'collected': 2,
 'it': 13,
 'supports': 29,
 'multiple': 17,
 'paradigms': 21,
 'including': 10,
 'structured': 28,
 'object': 18,
 'oriented': 20,
 'functional': 6}

In [22]:
doc_matrix[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### Lets take simple dataframe for better understanding on this encode

In [23]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})


In [24]:
encode_df = pd.DataFrame(data)
encode_df

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [26]:
bow = CountVectorizer()
doc_matrix = bow.fit_transform(data['text'])



In [29]:
doc_matrix[0].toarray() # Below Encoding is for for first row in dataframe ,for "people watch cricket" it will be 1 and rest will be 0

array([[0, 1, 0, 1, 1]], dtype=int64)

In [32]:
mix = CountVectorizer(ngram_range=(1,2)) # here 1,2 means it will be single word and double word combination for encoding
mix_matrix = mix.fit_transform(encode_df['text'])
mix.vocabulary_

{'people': 6,
 'watch': 9,
 'cricket': 1,
 'people watch': 8,
 'watch cricket': 10,
 'cricket watch': 3,
 'give': 4,
 'comment': 0,
 'people give': 7,
 'give comment': 5,
 'cricket give': 2}

In [35]:
mix_matrix[0].toarray()

array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1]], dtype=int64)